import os
import sys

IS_WIN = sys.platform.startswith('win')
IS_MAC = sys.platform == 'darwin'

VERSAO_ATUAL = "v2.0.1"
APP_NAME = "Sync DJ Tools Suite"

# --- ESTILOS GLOBAIS ---
# Fontes
FONT_FAMILY = "Consolas"

# Cores
COLOR_BG_DARK = "#111111" # Fundo principal
COLOR_TEXT_NORMAL = "#FFFFFF"
COLOR_TEXT_MUTED = "#AAAAAA"
COLOR_ERROR = "#FF5555" # Cor para mensagens de erro
COLOR_SWITCH_OFF = "#555555"

# Raio do Canto
CORNER_RADIUS_NONE = 0

URL_DOACAO = "https://linktr.ee/leh.deejay82"
GITHUB_API_URL = "https://api.github.com/repos/rcsilva1979/sync-dj"
GITHUB_RELEASE_URL = "https://github.com/rcsilva1979/sync-dj/releases"
LATEST_RELEASE_API = "https://api.github.com/repos/rcsilva1979/sync-dj/releases/latest"

def _load_github_token():
    """Carrega o token de um arquivo local não versionado."""
    token_file = os.path.join(os.path.dirname(__file__), "_github_token.txt")
    if os.path.exists(token_file):
        with open(token_file, "r") as f:
            return f.read().strip()
    return ""

GITHUB_TOKEN = _load_github_token()

STRINGS = {
    "pt": {
        "all_dbs_label": ">>> TODOS OS BANCOS LOCALIZADOS <<<",
        "backup": "Fazer Backup Automático",
        "browse": "Procurar",
        "btn_no": "Lembrar Depois",
        "btn_yes": "Baixar Agora",
        "cancel_btn": "Cancelar Sincronização",
        "cancel_msg": "Deseja realmente interromper a sincronização?\n\nNenhuma alteração será gravada no Engine DJ.",
        "cancel_title": "Confirmar",
        "close_btn": "Fechar",
        "collection_name": "- MY COLLECTION", # Nome real da playlist
        "collection_name_display": "- MY COLLECTION", # Nome para exibição
        "discovery_btn": "Descobrir Músicas (Atualizar Tags & Capas)",
        "discovery_title": "Shazam Song Discovery",
        "discovery_folder_label": "Pasta para verificar músicas:",
        "discovery_include_cover": "Incluir Capa (Artwork)",
        "discovery_rename_files": "Renomear Arquivos (Artista - Título)",
        "discovery_overwrite_tags": "Sobrescrever Tags Existentes",
        "discovery_simulation_mode": "Modo Simulação (Não alterar arquivos)",
        "discovery_btn_action": "Descobrir e Corrigir Tags",
        "discovery_status_waiting": "Aguardando início...",
        "confirm_playlist_msg": "A playlist alvo selecionada ({playlist}) é diferente do nome da pasta ({folder}).\n\nIsso irá REESTRUTURAR a playlist '{playlist}' para espelhar a pasta.\n\nDeseja continuar?",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "content_title": "Conteúdo: {title}",
        "csv_converter_title": "Engine DJ CSV para Virtual DJ XML Converter",
        "db_file": "Banco de Dados (m.db):",
        "debug_checkbox": "DEBUG",
        "donation_text": "Este app te ajudou? Gostaria de me incentivar a mante-lo atualizado\nme pagando um cafezinho? ☕ Clique aqui ☺️",
        "engine_dbs_detected": "Bancos de Dados Engine DJ encontrados: {count}",
        "engine_sync_title": "ENGINE DJ SYNC",
        "error_conversion_title": "Erro na Conversão",
        "error_db": "Erro: Arquivo m.db não encontrado!",
        "error_db_file_not_found_vdj_export": "Erro: Arquivo de banco de dados não encontrado.",
        "error_different_drives": "Erro: A pasta de músicas e o banco de dados devem estar no mesmo disco (ex: ambos no C: ou ambos no D:).",
        "error_export_title": "Erro de Exportação",
        "error_exporting_playlist_info": "Erro ao exportar informações da playlist: {error}",
        "error_exporting_playlist_info_detail": "Não foi possível exportar as informações da playlist:\n{error}",
        "error_exporting_vdj_generic": "Erro na exportação: {error}",
        "error_generating_xml_vdj": "Não foi possível gerar o arquivo XML:\n{error}",
        "error_import_title": "Erro de Importação",
        "error_importing_vdj_playlist": "Erro: {error}",
        "error_importing_vdj_playlist_detail": "Não foi possível processar a playlist:\n{error}",
        "error_loading_playlists_vdj_export": "Erro ao carregar playlists: {error}",
        "error_no_db_on_drive": "Erro: Não foi localizado um banco de dados Engine DJ no disco {drive}.\nCertifique-se de que a pasta 'Engine Library' existe na raiz deste disco.",
        "error_paths": "Por favor, selecione as pastas antes de iniciar.",
        "error_processing_csv": "Ocorreu um erro ao processar o CSV:\n{error}",
        "error_reading_xml": "Erro ao ler XML: {error}",
        "error_select_engine_db": "Por favor, selecione um banco de dados Engine DJ válido.",
        "error_select_playlist_to_export": "Por favor, selecione uma playlist para exportar.",
        "error_select_playlist_to_import_vdj": "Por favor, selecione uma playlist para importar.",
        "error_select_valid_playlist_to_view": "Selecione uma playlist válida para visualizar seu conteúdo.",
        "error_select_valid_vdj_xml": "Selecione um arquivo XML do VirtualDJ válido.",
        "error_title": "Erro",
        "error_vdj_dest_not_found": "Pasta de destino do VirtualDJ não identificada.",
        "export_engine_info_btn": "Exportar Info da Playlist (Engine)",
        "export_title": "Exportar",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestino: {dest_path}",
        "exported_tracks_from_dbs_count": "Exportadas {num_tracks} faixas de {num_dbs} banco(s).",
        "hotcue": "Importar Hotcues do MP3 (Mixed In Key / Serato)",
        "hotcue_import_btn": "Importar Hotcues MP3 TAG (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescrever hotcues existentes no Engine DJ [PROCESSO DEMORADO]",
        "hybrid_playlist_detected_msg": " (Playlist Híbrida detectada em {num_drives} discos)",
        "importing_tracks_to_drive": "Importando {count} faixas para o banco do disco {drive}...",
        "log_checkbox": "LOG",
        "mik_error_reading_hotcues": "Falha ao ler hotcues:",
        "mik_filename_label": "Nome do Arquivo:",
        "mik_hotcue_left_col_header": "Hotcues (1-4)",
        "mik_hotcue_right_col_header": "Hotcues (5-8)",
        "mik_import_btn_action": "Iniciar Importação de Tags Mixed In Key",
        "mik_list_btn": "Listar Músicas e Hotcues (Tags)",
        "mik_location_label": "Localização:",
        "mik_no_hotcues_found": "Nenhum Hotcue encontrado na tag MP3.",
        "mik_sync_title": "Mixed In Key Hotcue Sync",
        "mirror_sync_btn": "Mirror Sync (Pasta → Engine DJ)",
        "multi_db_mode_active": "Modo Multi-Banco ativo ({count} discos).",
        "music_folder": "Pasta de Músicas (PC):",
        "music_list_header": "Lista de Músicas: {title}",
        "no_playlists_found_generic": "Nenhuma playlist encontrada.",
        "no_tracks_found_in_playlist_vdj_export": "Nenhuma faixa encontrada em '{playlist_name}'.",
        "no_tracks_in_playlist": "Nenhuma música encontrada nesta playlist.",
        "not_found": "Não localizada",
        "playlist": "Playlist Raiz:",
        "playlists_loaded_count": "{count} playlists carregadas.",
        "remover_orfas": "Remover músicas órfãs (faltantes no PC) da Playlist e da Coleção",
        "settings_title": "Configurações / Preferências",
        "preferences_label": "Preferências:",
        "show_report_checkbox": "Exibir relatório ao final",
        "auto_update_checkbox": "Verificar atualização automaticamente",
        "select_playlist_full_path": "Selecionar Playlist (Caminho Completo):",
        "select_playlist_to_start": "Selecione a playlist para começar",
        "select_tool_prompt": "Selecione a ferramenta desejada:",
        "select_vdj_playlist_label": "Selecionar Playlist do VirtualDJ (.vdjfolder):",
        "start_import_vdj_btn": "Iniciar Importação para o Engine DJ",
        "status_backup": "Criando backup do banco de dados...",
        "status_cancelled": "Sincronização cancelada pelo usuário.",
        "status_collecting_tracks_vdj": "Coletando faixas de '{playlist_name}'...",
        "status_counting": "Contando arquivos de áudio...",
        "status_done": "Sincronização concluída com sucesso!",
        "relocate_lost_tracks_btn": "Reencontrar Músicas Perdidas (Fix Paths)",
        "relocate_title": "Relocação de Músicas Perdidas",
        "search_folder_label": "Pasta para busca de arquivos (Scan recursivo):",
        "status_scanning_missing": "Identificando arquivos ausentes na playlist...",
        "status_searching_files": "Buscando arquivos na pasta selecionada...",
        "status_relocating": "Relocando: {filename}",
        "success_relocate_detail": "Relocação concluída!\n\nArquivos analisados: {total}\nArquivos ausentes: {missing}\nArquivos recuperados: {relocated}",
        "error_no_missing_found": "Todas as músicas desta playlist foram localizadas no disco!",
        "skipped_duplicate": "Já existem na coleção (Caminho duplicado)",
        "skipped_different_drive": "Encontrados em outro disco (Não permitido)",
        "skipped_not_found": "Não encontrados na pasta selecionada",
        "relocate_mode_label": "Ação ao encontrar arquivos ausentes:",
        "relocate_mode_alert": "Apenas alertar (Sem alterações)",
        "relocate_mode_copy": "Restaurar: Copiar arquivo para a pasta original (Conserva o banco de dados)",
        "relocate_mode_update": "Relocar: Atualizar caminho no banco de dados (Corrige o banco de dados)",
        "relocate_just_verify_label": "Apenas Verificar (Sem alterações / Gerar Relatório)",
        "relocate_btn_action": "Iniciar Busca e Relocação",
        "fuzzy_search_label": "Busca inteligente (Arquivos renomeados ou nome parcial)",
        "fuzzy_action_copy": "Copiar arquivo para o local antigo",
        "fuzzy_action_move": "Mover arquivo para o local antigo",
        "fuzzy_action_update": "Atualizar no banco de dados o novo local",
        "fuzzy_action_rename": "Renomear o arquivo encontrado (Mesma pasta)",
        "status_export_vdj_complete": "Exportação de '{playlist_name}' concluída (placeholder).",
        "status_exporting_vdj": "Exportando '{playlist_name}' para {dest_path}...",
        "status_extracting_playlist_info": "Extraindo informações da playlist '{playlist_name}'...",
        "status_fase1": "Fase 1: Mapeando arquivos ({current}/{total})...",
        "status_fase2": "Fase 2: Reconstruindo a árvore de Playlists...",
        "status_hotcue": "Importando hotcue: {filename}...",
        "status_idle": "Pronto para iniciar. Verifique se o Engine está fechado.",
        "status_import_complete": "Importação concluída: {processed_count} faixas em {num_drives} discos.",
        "status_playlist_info_exported": "Informações da playlist exportadas para: {output_file_path}",
        "status_reading_vdj_playlist": "Lendo playlist VDJ...",
        "status_saving": "Fase 3: Gravando no banco de dados...",
        "success_msg": "Operação finalizada!\nMúsicas novas injetadas: {novas}\nMúsicas apagadas (órfãs): {apagadas}\nSua coleção foi sincronizada.",
        "success_playlist_exported_vdj_status": "Sucesso! '{playlist_name}' exportada.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exportada ({num_tracks} faixas unificadas).\n\nArquivo: {output_file_path}",
        "success_title": "Sucesso",
        "success_tracks_converted": "Sucesso! {count} músicas convertidas.",
        "success_vdj_import": "A playlist '{playlist_name}' foi distribuída e sincronizada com sucesso nos discos detectados!",
        "success_xml_generated": "Playlist XML gerada com sucesso!\n{count} músicas processadas.",
        "sync_btn": "Iniciar Sincronização",
        "sync_vdj_btn": "Sync VDJ (Engine DJ ⟷ Virtual DJ)",
        "title": "Engine DJ - Mirror Sync",
        "update_msg": "Uma nova versão do Sync DJ está disponível!\n\nSua versão: {}\nNova versão: {}\n\nDeseja baixar a atualização agora?",
        "update_title": "Atualização Disponível!",
        "vdj_back_btn": "Voltar para Sync DJ",
        "vdj_config_label": "Configuração: {settings}",
        "vdj_export_btn": "Exportar Playlist do Engine DJ para o VDJ",
        "vdj_export_btn_action": "Exportar Playlist Selecionada",
        "vdj_export_success_msg_detail": "Playlist exportada para o Virtual DJ!\n{num_tracks} músicas processadas.\n{hybrid_msg}\n\nArquivo: {output_file}",
        "vdj_import_btn": "Importar Playlist do VDJ para o Engine DJ",
        "vdj_mylists_label": "MyLists:",
        "vdj_mylists_not_found": "Subpastas 'MyLists' não localizadas nos discos.",
        "vdj_sync_description": "Interface de Sincronização Virtual DJ",
        "vdj_sync_title": "Sync VDJ",
        "vdj_target_label": "Destino no Virtual DJ:",
        "view_tracks_btn": "Ver Músicas",
        "warning_no_tracks_in_xml": "Nenhuma faixa encontrada no arquivo XML.",
        "warning_title": "Aviso",
        "will_be_created_suffix": " (Nova, será criada)",
    },
    "en": {
        "all_dbs_label": ">>> ALL LOCATED DATABASES <<<",
        "backup": "Auto-Backup Database",
        "browse": "Browse",
        "btn_no": "Remind Me Later",
        "btn_yes": "Download Now",
        "cancel_btn": "Cancel Synchronization",
        "cancel_msg": "Do you really want to stop the synchronization?\n\nNo changes will be saved to the Engine DJ",
        "cancel_title": "Confirm",
        "close_btn": "Close",
        "collection_name": "- MY COLLECTION", # Actual playlist name
        "collection_name_display": "- MY COLLECTION", # Display name
        "discovery_btn": "Discovery Song (Fix Tags & Covers)",
        "discovery_title": "Shazam Song Discovery",
        "discovery_folder_label": "Folder to check songs:",
        "discovery_include_cover": "Include Cover (Artwork)",
        "discovery_rename_files": "Rename Files (Artist - Title)",
        "discovery_overwrite_tags": "Overwrite Existing Tags",
        "discovery_simulation_mode": "Simulation Mode (Do not change files)",
        "discovery_btn_action": "Discovery and Fix Tags",
        "discovery_status_waiting": "Waiting to start...",
        "confirm_playlist_msg": "The selected target playlist ({playlist}) is different from the folder name ({folder}).\n\nThis will RESTRUCTURE the playlist '{playlist}' to mirror the folder.\n\nDo you want to continue?",
        "confirm_playlist_title": "Confirm Root Playlist",
        "content_title": "Content: {title}",
        "csv_converter_title": "Engine DJ CSV to Virtual DJ XML Converter",
        "db_file": "Database File (m.db):",
        "debug_checkbox": "DEBUG",
        "donation_text": "Did this app help you? Would you like to encourage me to keep it\nupdated by buying me a coffee? ☕ Click here ☺️",
        "engine_dbs_detected": "Engine DJ Databases found: {count}",
        "engine_sync_title": "ENGINE DJ SYNC",
        "error_conversion_title": "Conversion Error",
        "error_db": "Error: m.db file not found!",
        "error_db_file_not_found_vdj_export": "Error: Database file not found.",
        "error_different_drives": "Error: The music folder and the database must be on the same drive (e.g., both on C: or both on D:).",
        "error_export_title": "Export Error",
        "error_exporting_playlist_info": "Error exporting playlist info: {error}",
        "error_exporting_playlist_info_detail": "Could not export playlist information:\n{error}",
        "error_exporting_vdj_generic": "Export error: {error}",
        "error_generating_xml_vdj": "Could not generate XML file:\n{error}",
        "error_import_title": "Import Error",
        "error_importing_vdj_playlist": "Error: {error}",
        "error_importing_vdj_playlist_detail": "Could not process the playlist:\n{error}",
        "error_loading_playlists_vdj_export": "Error loading playlists: {error}",
        "error_no_db_on_drive": "Error: No Engine DJ database found on drive {drive}.\nMake sure the 'Engine Library' folder exists on the root of this drive.",
        "error_paths": "Please select the paths before starting.",
        "error_processing_csv": "An error occurred while processing the CSV:\n{error}",
        "error_reading_xml": "Error reading XML: {error}",
        "error_select_engine_db": "Please select a valid Engine DJ database.",
        "error_select_playlist_to_export": "Please select a playlist to export.",
        "error_select_playlist_to_import_vdj": "Please select a playlist to import.",
        "error_select_valid_playlist_to_view": "Select a valid playlist to view its content.",
        "error_select_valid_vdj_xml": "Select a valid VirtualDJ XML file.",
        "error_title": "Error",
        "error_vdj_dest_not_found": "VirtualDJ destination folder not identified.",
        "export_engine_info_btn": "Export Playlist Info (Engine)",
        "export_title": "Export",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestination: {dest_path}",
        "exported_tracks_from_dbs_count": "Exported {num_tracks} tracks from {num_dbs} database(s).",
        "hotcue": "Import Hotcues from MP3 (Mixed In Key / Serato)",
        "hotcue_import_btn": "Import Hotcues MP3 TAG (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Overwrite existing hotcues in Engine DJ [SLOW PROCESS]",
        "hybrid_playlist_detected_msg": " (Hybrid Playlist detected on {num_drives} drives)",
        "importing_tracks_to_drive": "Importing {count} tracks to drive {drive} database...",
        "log_checkbox": "LOG",
        "mik_error_reading_hotcues": "Failed to read hotcues:",
        "mik_filename_label": "Filename:",
        "mik_hotcue_left_col_header": "Hotcues (1-4)",
        "mik_hotcue_right_col_header": "Hotcues (5-8)",
        "mik_import_btn_action": "Start Mixed In Key Tag Import",
        "mik_list_btn": "List Songs and Hotcues (Tags)",
        "mik_location_label": "Location:",
        "mik_no_hotcues_found": "No Hotcue found in MP3 tag.",
        "mik_sync_title": "Mixed In Key Hotcue Sync",
        "mirror_sync_btn": "Mirror Sync (Folder → Engine DJ)",
        "multi_db_mode_active": "Multi-Database mode active ({count} drives).",
        "music_folder": "Music Folder (Computer):",
        "music_list_header": "Music List: {title}",
        "no_playlists_found_generic": "No playlists found.",
        "no_tracks_found_in_playlist_vdj_export": "No tracks found in '{playlist_name}'.",
        "no_tracks_in_playlist": "No tracks found in this playlist.",
        "not_found": "Not found",
        "playlist": "Root Playlist:",
        "playlists_loaded_count": "{count} playlists loaded.",
        "remover_orfas": "Remove orphan tracks (missing from PC) from Playlist and Collection",
        "settings_title": "Settings / Preferences",
        "preferences_label": "Preferences:",
        "show_report_checkbox": "Show report at the end",
        "auto_update_checkbox": "Check for updates automatically",
        "select_playlist_full_path": "Select Playlist (Full Path):",
        "select_playlist_to_start": "Select playlist to start",
        "select_tool_prompt": "Select the desired tool:",
        "select_vdj_playlist_label": "Select VirtualDJ Playlist (.vdjfolder):",
        "start_import_vdj_btn": "Start Import to Engine DJ",
        "status_backup": "Creating database backup...",
        "status_cancelled": "Synchronization cancelled by user.",
        "status_collecting_tracks_vdj": "Collecting tracks from '{playlist_name}'...",
        "status_counting": "Counting audio files...",
        "status_done": "Synchronization completed successfully!",
        "relocate_lost_tracks_btn": "Relocate Lost Tracks (Fix Paths)",
        "relocate_title": "Relocate Lost Tracks",
        "search_folder_label": "Folder to search for files (Recursive Scan):",
        "status_scanning_missing": "Identifying missing files in playlist...",
        "status_searching_files": "Searching for files in selected folder...",
        "status_relocating": "Relocating: {filename}",
        "success_relocate_detail": "Relocation complete!\n\nFiles analyzed: {total}\nMissing files: {missing}\nFiles recovered: {relocated}",
        "error_no_missing_found": "All tracks in this playlist were found on disk!",
        "skipped_duplicate": "Already in collection (Duplicate path)",
        "skipped_different_drive": "Found on another drive (Not allowed)",
        "skipped_not_found": "Not found in selected folder",
        "relocate_mode_label": "Action when missing files are found:",
        "relocate_mode_alert": "Alert only (No changes)",
        "relocate_mode_copy": "Restore: Copy file to original folder (Keep database)",
        "relocate_mode_update": "Relocate: Update path in database (Fix database)",
        "relocate_btn_action": "Start Search and Relocate",
        "relocate_just_verify_label": "Verify Only (No changes / Generate Report)",
        "fuzzy_search_label": "Smart search (Renamed or partial filenames)",
        "fuzzy_action_copy": "Copy file to old location",
        "fuzzy_action_move": "Move file to old location",
        "fuzzy_action_update": "Update new location in database",
        "fuzzy_action_rename": "Rename file (Same folder)",
        "status_export_vdj_complete": "Export of '{playlist_name}' completed (placeholder).",
        "status_exporting_vdj": "Exporting '{playlist_name}' to {dest_path}...",
        "status_extracting_playlist_info": "Extracting playlist info for '{playlist_name}'...",
        "status_fase1": "Phase 1: Mapping files ({current}/{total})...",
        "status_fase2": "Phase 2: Rebuilding Playlist tree...",
        "status_hotcue": "Importing hotcue: {filename}...",
        "status_idle": "Ready to start. Make sure Engine DJ is closed.",
        "status_import_complete": "Import completed: {processed_count} tracks on {num_drives} drives.",
        "status_playlist_info_exported": "Playlist info exported to: {output_file_path}",
        "status_reading_vdj_playlist": "Reading VDJ playlist...",
        "status_saving": "Phase 3: Saving to database...",
        "success_msg": "Operation finished!\nNew tracks injected: {novas}\nOrphan tracks removed: {apagadas}\nYour collection is synced.",
        "success_playlist_exported_vdj_status": "Success! '{playlist_name}' exported.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exported ({num_tracks} unified tracks).\n\nFile: {output_file_path}",
        "success_title": "Success",
        "success_tracks_converted": "Success! {count} tracks converted.",
        "success_vdj_import": "Playlist '{playlist_name}' successfully distributed and synced across detected drives!",
        "success_xml_generated": "Playlist XML successfully generated!\n{count} tracks processed.",
        "sync_btn": "Start Synchronization",
        "sync_vdj_btn": "Sync VDJ (Engine DJ ⟷ Virtual DJ)",
        "title": "Engine DJ - Mirror Sync",
        "update_msg": "A new version of Sync DJ is available!\n\nYour version: {}\nNew version: {}\n\nWould you like to download it now?",
        "update_title": "Update Available!",
        "vdj_back_btn": "Back to Sync DJ",
        "vdj_config_label": "Configuration: {settings}",
        "vdj_export_btn": "Export Engine DJ Playlist to VDJ",
        "vdj_export_btn_action": "Export Selected Playlist",
        "vdj_export_success_msg_detail": "Playlist exported to Virtual DJ!\n{num_tracks} tracks processed.\n{hybrid_msg}\n\nFile: {output_file}",
        "vdj_import_btn": "Import VDJ Playlist to Engine DJ",
        "vdj_mylists_label": "MyLists:",
        "vdj_mylists_not_found": "MyLists subfolders not found on drives.",
        "vdj_sync_description": "Virtual DJ Synchronization Interface",
        "vdj_sync_title": "Sync VDJ",
        "vdj_target_label": "Destination in Virtual DJ:",
        "view_tracks_btn": "View Tracks",
        "warning_no_tracks_in_xml": "No tracks found in the XML file.",
        "warning_title": "Warning",
        "will_be_created_suffix": " (New, will be created)",
    },
    "es": {
        "all_dbs_label": ">>> TODAS LAS BASES DE DATOS LOCALIZADAS <<<",
        "backup": "Hacer Copia de Seguridad Automática",
        "browse": "Buscar",
        "btn_no": "Recordarme Más Tarde",
        "btn_yes": "Descargar Ahora",
        "cancel_btn": "Cancelar Sincronización",
        "cancel_msg": "¿Realmente desea interrumpir la sincronización?\n\nNo se guardarán cambios en Engine DJ",
        "cancel_title": "Confirmar",
        "close_btn": "Cerrar",
        "collection_name": "- MY COLLECTION", # Nombre real de la playlist
        "collection_name_display": "- MY COLLECTION", # Nombre para mostrar
        "discovery_btn": "Descobrir Canciones (Corregir Tags & Capas)",
        "discovery_title": "Shazam Song Discovery",
        "discovery_folder_label": "Carpeta para verificar canciones:",
        "discovery_include_cover": "Incluir Portada (Artwork)",
        "discovery_rename_files": "Renombrar Archivos (Artista - Título)",
        "discovery_overwrite_tags": "Sobrescribir Etiquetas Existentes",
        "discovery_simulation_mode": "Modo Simulación (No alterar archivos)",
        "discovery_btn_action": "Descobrir e Corregir Etiquetas",
        "discovery_status_waiting": "Esperando inicio...",
        "confirm_playlist_msg": "La lista de reproducción de destino seleccionada ({playlist}) é diferente del nombre de la carpeta ({folder}).\n\nEsto REESTRUCTURARÁ la lista '{playlist}' para reflejar la carpeta.\n\n¿Desea continuar?",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "content_title": "Contenido: {title}",
        "csv_converter_title": "Convertidor de CSV de Engine DJ a XML de Virtual DJ",
        "db_file": "Base de Datos (m.db):",
        "debug_checkbox": "DEBUG",
        "donation_text": "¿Te ha resultado útil esta aplicación? ¿Te gustaría animarme a seguir\nactualizándola invitándome a un café? ☕ Haz clic aquí ☺️",
        "engine_dbs_detected": "Bases de Datos Engine DJ encontradas: {count}",
        "engine_sync_title": "ENGINE DJ SYNC",
        "error_conversion_title": "Error de Conversión",
        "error_db": "¡Error: Archivo m.db no encontrado!",
        "error_db_file_not_found_vdj_export": "Error: Archivo de base de datos no encontrado.",
        "error_different_drives": "Error: La carpeta de música y la base de datos deben estar en el mismo disco (ej: ambos en C: o ambos en D:).",
        "error_export_title": "Error de Exportación",
        "error_exporting_playlist_info": "Error al exportar información de la playlist: {error}",
        "error_exporting_playlist_info_detail": "No se pudo exportar la información de la playlist:\n{error}",
        "error_exporting_vdj_generic": "Error de exportación: {error}",
        "error_generating_xml_vdj": "No se pudo generar el archivo XML:\n{error}",
        "error_import_title": "Error de Importación",
        "error_importing_vdj_playlist": "Error: {error}",
        "error_importing_vdj_playlist_detail": "No se pudo procesar la playlist:\n{error}",
        "error_loading_playlists_vdj_export": "Error al cargar playlists: {error}",
        "error_paths": "Por favor, seleccione las rutas antes de empezar.",
        "error_processing_csv": "Ocurrió un error al procesar el CSV:\n{error}",
        "error_reading_xml": "Error al leer XML: {error}",
        "error_select_engine_db": "Por favor, seleccione una base de datos Engine DJ válida.",
        "error_select_playlist_to_export": "Por favor, seleccione una playlist para exportar.",
        "error_select_playlist_to_import_vdj": "Por favor, seleccione una playlist para importar.",
        "error_select_valid_playlist_to_view": "Seleccione una playlist válida para ver su contenido.",
        "error_select_valid_vdj_xml": "Seleccione un archivo XML de VirtualDJ válido.",
        "error_title": "Error",
        "error_vdj_dest_not_found": "Carpeta de destino de VirtualDJ no identificada.",
        "export_engine_info_btn": "Exportar Info de la Playlist (Engine)",
        "export_title": "Exportar",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestino: {dest_path}",
        "exported_tracks_from_dbs_count": "Exportadas {num_tracks} pistas de {num_dbs} base(s) de datos.",
        "hotcue": "Importar Hotcues del MP3 (Mixed In Key / Serato)",
        "hotcue_import_btn": "Importar Hotcues MP3 TAG (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescribir hotcues existentes en Engine DJ [PROCESO DEMORADO]",
        "hybrid_playlist_detected_msg": " (Playlist Híbrida detectada en {num_drives} discos)",
        "importing_tracks_to_drive": "Importando {count} pistas al banco del disco {drive}...",
        "log_checkbox": "LOG",
        "mik_error_reading_hotcues": "Fallo al leer hotcues:",
        "mik_filename_label": "Nombre de Archivo:",
        "mik_hotcue_left_col_header": "Hotcues (1-4)",
        "mik_hotcue_right_col_header": "Hotcues (5-8)",
        "mik_import_btn_action": "Iniciar Importación de Tags Mixed In Key",
        "mik_list_btn": "Listar Canciones y Hotcues (Tags)",
        "mik_location_label": "Ubicación:",
        "mik_no_hotcues_found": "Ningún Hotcue encontrado en la etiqueta MP3.",
        "mik_sync_title": "Sincronización de Hotcues de Mixed In Key",
        "mirror_sync_btn": "Mirror Sync (Carpeta → Engine DJ)",
        "multi_db_mode_active": "Modo Multi-Base de Datos activo ({count} discos).",
        "music_folder": "Carpeta de Música (PC):",
        "music_list_header": "Lista de Canciones: {title}",
        "no_playlists_found_generic": "Ninguna playlist encontrada.",
        "no_tracks_found_in_playlist_vdj_export": "Ninguna pista encontrada en '{playlist_name}'.",
        "no_tracks_in_playlist": "Ninguna canción encontrada en esta playlist.",
        "not_found": "No encontrada",
        "playlist": "Playlist Raiz:",
        "playlists_loaded_count": "{count} playlists cargadas.",
        "remover_orfas": "Eliminar canciones huérfanas de la lista de reproducción y de la colección",
        "settings_title": "Configuración / Preferencias",
        "preferences_label": "Preferencias:",
        "show_report_checkbox": "Mostrar informe al final",
        "auto_update_checkbox": "Buscar actualizaciones automáticamente",
        "select_playlist_full_path": "Seleccionar Playlist (Ruta Completa):",
        "select_playlist_to_start": "Seleccione la playlist para empezar",
        "select_tool_prompt": "Seleccione la herramienta deseada:",
        "select_vdj_playlist_label": "Seleccionar Playlist de VirtualDJ (.vdjfolder):",
        "start_import_vdj_btn": "Iniciar Importación a Engine DJ",
        "status_backup": "Creando copia de seguridad...",
        "status_cancelled": "Sincronización cancelada por el usuario.",
        "status_collecting_tracks_vdj": "Recopilando pistas de '{playlist_name}'...",
        "status_counting": "Contando arquivos de audio...",
        "status_done": "¡Sincronización completada con éxito!",
        "relocate_lost_tracks_btn": "Reencontrar Canciones Perdidas",
        "relocate_title": "Relocalización de Canciones Perdidas",
        "search_folder_label": "Carpeta para buscar archivos (Escaneo recursivo):",
        "status_scanning_missing": "Identificando archivos ausentes en la lista...",
        "status_searching_files": "Buscando archivos en la carpeta seleccionada...",
        "status_relocating": "Relocalizando: {filename}",
        "success_relocate_detail": "¡Relocalización completada!\n\nArchivos analizados: {total}\nArchivos ausentes: {missing}\nArchivos recuperados: {relocated}",
        "error_no_missing_found": "¡Todas las canciones de esta lista fueron localizadas en el disco!",
        "skipped_duplicate": "Ya existen en la colección (Ruta duplicada)",
        "skipped_different_drive": "Encontrados en otro disco (No permitido)",
        "skipped_not_found": "No encontrados en la carpeta seleccionada",
        "relocate_mode_label": "Acción al encontrar archivos faltantes:",
        "relocate_mode_alert": "Sólo alertar (Sin cambios)",
        "relocate_mode_copy": "Restaurar: Copiar archivo a la carpeta original (Conserva la base de datos)",
        "relocate_mode_update": "Relocalizar: Actualizar ruta en la base de datos (Corrige la base de datos)",
        "relocate_btn_action": "Iniciar Búsqueda y Relocalización",
        "relocate_just_verify_label": "Solo verificar (Sin cambios / Generar informe)",
        "fuzzy_search_label": "Búsqueda inteligente (Archivos renombrados o nombre parcial)",
        "fuzzy_action_copy": "Copiar archivo a la ubicación antigua",
        "fuzzy_action_move": "Mover archivo a la ubicación antigua",
        "fuzzy_action_update": "Actualizar nueva ubicación en la base de datos",
        "fuzzy_action_rename": "Renombrar archivo (En la misma carpeta)",
        "status_export_vdj_complete": "Exportación de '{playlist_name}' completada (marcador de posición).",
        "status_exporting_vdj": "Exportando '{playlist_name}' a {dest_path}...",
        "status_extracting_playlist_info": "Extrayendo información de la playlist '{playlist_name}'...",
        "status_fase1": "Phase 1: Mapeando archivos ({current}/{total})...",
        "status_fase2": "Phase 2: Reconstruyendo árbol de Playlists...",
        "status_hotcue": "Importando hotcue: {filename}...",
        "status_idle": "Listo para empezar. Cierre Engine DJ antes.",
        "status_import_complete": "Importación completada: {processed_count} pistas en {num_drives} discos.",
        "status_playlist_info_exported": "Información de la playlist exportada a: {output_file_path}",
        "status_reading_vdj_playlist": "Leyendo playlist VDJ...",
        "status_saving": "Phase 3: Guardando en la base de datos...",
        "success_msg": "¡Operación finalizada!\nNuevas canciones inyectadas: {novas}\nCanciones eliminadas (huérfanas): {apagadas}\nSu colección está sincronizada.",
        "success_playlist_exported_vdj_status": "¡Éxito! '{playlist_name}' exportada.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exportada ({num_tracks} pistas unificadas).\n\nArchivo: {output_file_path}",
        "success_title": "Éxito",
        "success_tracks_converted": "¡Éxito! {count} canciones convertidas.",
        "success_vdj_import": "¡La playlist '{playlist_name}' fue distribuida y sincronizada con éxito en los discos detectados!",
        "success_xml_generated": "¡Playlist XML generada con éxito!\n{count} canciones procesadas.",
        "sync_btn": "Iniciar Sincronización",
        "sync_vdj_btn": "Sync VDJ (Engine DJ ⟷ Virtual DJ)",
        "title": "Engine DJ - Mirror Sync",
        "update_msg": "¡Una nova versión de Sync DJ está disponible!\n\nTu versão: {}\nNueva versión: {}\n\n¿Quieres descargarla ahora?",
        "update_title": "¡Actualización Disponible!",
        "vdj_config_label": "Configuración: {settings}",
        "vdj_export_btn": "Exportar Playlist de Engine DJ a VDJ",
        "vdj_export_btn_action": "Exportar Playlist Seleccionada",
        "vdj_export_success_msg_detail": "¡Playlist exportada a Virtual DJ!\n{num_tracks} pistas procesadas.\n{hybrid_msg}\n\nArchivo: {output_file}",
        "vdj_import_btn": "Importar Playlist de VDJ a Engine DJ",
        "vdj_mylists_label": "MisListas:",
        "vdj_mylists_not_found": "Subcarpetas 'MyLists' no encontradas en los discos.",
        "vdj_sync_description": "Interfaz de Sincronización Virtual DJ",
        "vdj_sync_title": "Sincronizar VDJ",
        "vdj_target_label": "Destino en Virtual DJ:",
        "view_tracks_btn": "Ver Canciones",
        "warning_no_tracks_in_xml": "Ninguna pista encontrada en el archivo XML.",
        "warning_title": "Advertencia",
        "will_be_created_suffix": " (Nova, Se Creará)",
    }
}