VERSAO_ATUAL = "v2.0.9"
URL_DOACAO = "https://linktr.ee/leh.deejay82"
GITHUB_API_URL = "https://api.github.com/repos/lehdeejay82/Engine-Sync/releases/latest"
GITHUB_RELEASE_URL = "https://github.com/lehdeejay81/Engine-Sync/releases/latest" # Corrected to lehdeejay81

STRINGS = {
    "pt": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Pasta de Músicas (PC):",
        "db_file": "Banco de Dados (m.db):",
        "playlist": "Playlist Raiz:",
        "backup": "Fazer Backup Automático",
        "status_backup": "Criando backup do banco de dados...",
        "hotcue": "Importar Hotcues do MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescrever hotcues existentes no Engine DJ [PROCESSO DEMORADO]",
        "remover_orfas": "Remover músicas órfãs (faltantes no PC) da Playlist e da Coleção",
        "status_hotcue": "Importando hotcue: {filename}...",
        "browse": "Procurar",
        "sync_btn": "Iniciar Sincronização",
        "cancel_btn": "Cancelar Sincronização",
        "cancel_title": "Confirmar",
        "cancel_msg": "Deseja realmente interromper a sincronização?\n\nNenhuma alteração será gravada no Engine DJ.",
        "status_cancelled": "Sincronização cancelada pelo usuário.",
        "status_idle": "Pronto para iniciar. Verifique se o Engine está fechado.",
        "status_counting": "Contando arquivos de áudio...",
        "status_fase1": "Fase 1: Mapeando arquivos ({current}/{total})...",
        "status_fase2": "Fase 2: Reconstruindo a árvore de Playlists...",
        "status_saving": "Fase 3: Gravando no banco de dados...",
        "status_cancelled": "Sincronização cancelada pelo usuário.",
        "status_done": "Sincronização concluída com sucesso!",
        "status_exporting_vdj": "Exportando '{playlist_name}' para {dest_path}...",
        "status_export_vdj_complete": "Exportação de '{playlist_name}' concluída (placeholder).",
        "status_extracting_playlist_info": "Extraindo informações da playlist '{playlist_name}'...",
        "status_playlist_info_exported": "Informações da playlist exportadas para: {output_file_path}",
        "status_reading_vdj_playlist": "Lendo playlist VDJ...",
        "status_collecting_tracks_vdj": "Coletando faixas de '{playlist_name}'...",
        "importing_tracks_to_drive": "Importando {count} faixas para o banco do disco {drive}...",
        "status_import_complete": "Importação concluída: {processed_count} faixas em {num_drives} discos.",
        "error_db": "Erro: Arquivo m.db não encontrado!",
        "error_paths": "Por favor, selecione as pastas antes de iniciar.",
        "error_different_drives": "Erro: A pasta de músicas e o banco de dados devem estar no mesmo disco (ex: ambos no C: ou ambos no D:).",
        "error_title": "Erro",
        "error_select_engine_db": "Por favor, selecione um banco de dados Engine DJ válido.",
        "error_db_file_not_found_vdj_export": "Erro: Arquivo de banco de dados não encontrado.",
        "error_select_playlist_to_export": "Por favor, selecione uma playlist para exportar.",
        "error_vdj_dest_not_found": "Pasta de destino do VirtualDJ não identificada.",
        "error_export_title": "Erro de Exportação",
        "error_exporting_playlist_info": "Erro ao exportar informações da playlist: {error}",
        "error_exporting_playlist_info_detail": "Não foi possível exportar as informações da playlist:\n{error}",
        "error_select_valid_playlist_to_view": "Selecione uma playlist válida para visualizar seu conteúdo.",
        "error_select_valid_vdj_xml": "Selecione um arquivo XML do VirtualDJ válido.",
        "error_import_title": "Erro de Importação",
        "error_importing_vdj_playlist": "Erro: {error}",
        "error_importing_vdj_playlist_detail": "Não foi possível processar a playlist:\n{error}",
        "error_exporting_vdj_generic": "Erro na exportação: {error}",
        "error_reading_xml": "Erro ao ler XML: {error}",
        "success_msg": "Operação finalizada!\nMúsicas novas injetadas: {novas}\nMúsicas apagadas (órfãs): {apagadas}\nSua coleção foi sincronizada.",
        "collection_name": "- MY COLLECTION", # Nome real da playlist
        "collection_name_display": "- MY COLLECTION", # Nome para exibição
        "engine_sync_title": "ENGINE DJ SYNC",
        "log_checkbox": "LOG",
        "debug_checkbox": "DEBUG",
        "select_playlist_full_path": "Selecionar Playlist (Caminho Completo):",
        "playlist_label": "Playlist Raiz:",
        "vdj_target_label": "Destino no Virtual DJ:",
        "vdj_export_btn_action": "Exportar Playlist Selecionada",
        "export_engine_info_btn": "Exportar Info da Playlist (Engine)",
        "will_be_created_suffix": " (Nova, será criada)",
        "donation_text": "Este app te ajudou? Gostaria de me incentivar a mante-lo atualizado\nme pagando um cafezinho? ☕ Clique aqui ☺️",
        "update_title": "Atualização Disponível!",
        "update_msg": "Uma nova versão do Engine Sync está disponível!\n\nSua versão: {}\nNova versão: {}\n\nDeseja baixar a atualização agora?",
        "btn_yes": "Baixar Agora",
        "btn_no": "Lembrar Depois",
        "success_title": "Sucesso",
        "success_playlist_exported_vdj_status": "Sucesso! '{playlist_name}' exportada.",
        "select_tool_prompt": "Selecione a ferramenta desejada:",
        "mirror_sync_btn": "Mirror Sync (Pasta → Engine DJ)",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "sync_vdj_btn": "Sync VDJ (Engine ⟷ Virtual DJ)",
        "confirm_playlist_msg": "A playlist alvo selecionada ({playlist}) é diferente do nome da pasta ({folder}).\n\nIsso irá REESTRUTURAR a playlist '{playlist}' para espelhar a pasta.\n\nDeseja continuar?",
        "dbs_found": "Bancos Engine localizados: {count}",
        "error_no_db_on_drive": "Erro: Não foi localizado um banco de dados Engine DJ no disco {drive}.\nCertifique-se de que a pasta 'Engine Library' existe na raiz deste disco.",
        "vdj_back_btn": "Voltar para Sync DJ",
        "vdj_export_btn": "Exportar Playlist do Engine DJ para o VDJ",
        "vdj_import_btn": "Importar Playlist do VDJ para o Engine DJ",
        "vdj_sync_title": "Sync VDJ",
        "vdj_sync_description": "Interface de Sincronização Virtual DJ",
        "vdj_config_label": "Configuração: {settings}",
        "engine_dbs_detected": "Bancos Engine detectados: {count}",
        "all_dbs_label": ">>> TODOS OS BANCOS LOCALIZADOS <<<",
        "not_found": "Não localizada",
        "vdj_mylists_label": "MyLists:",
        "vdj_mylists_not_found": "Subpastas 'MyLists' não localizadas nos discos.",
        "content_title": "Conteúdo: {title}",
        "music_list_header": "Lista de Músicas: {title}",
        "no_tracks_in_playlist": "Nenhuma música encontrada nesta playlist.",
        "no_playlists_found_in_db_vdj_export": "Nenhuma playlist encontrada neste banco de dados.",
        "error_loading_playlists_vdj_export": "Erro ao carregar playlists: {error}",
        "multi_db_mode_active": "Modo Multi-Banco ativo ({count} discos).",
        "playlists_loaded_count": "{count} playlists carregadas.",
        "no_playlists_found_generic": "Nenhuma playlist encontrada.",
        "error_select_playlist_to_import_vdj": "Por favor, selecione uma playlist para importar.",
        "no_tracks_found_in_playlist_vdj_export": "Nenhuma faixa encontrada em '{playlist_name}'.",
        "vdj_export_success_msg_detail": "Playlist exportada para o Virtual DJ!\n{num_tracks} músicas processadas.\n{hybrid_msg}\n\nArquivo: {output_file}",
        "hybrid_playlist_detected_msg": " (Playlist Híbrida detectada em {num_drives} discos)",
        "close_btn": "Fechar",
        "select_vdj_playlist_label": "Selecionar Playlist do VirtualDJ (.vdjfolder):",
        "view_tracks_btn": "Ver Músicas",
        "dbs_found_label": "Bancos de Dados Engine DJ Localizados: {dbs_info}",
        "select_playlist_to_start": "Selecione a playlist para começar",
        "start_import_vdj_btn": "Iniciar Importação para o Engine DJ",
        "warning_title": "Aviso",
        "warning_no_tracks_in_xml": "Nenhuma faixa encontrada no arquivo XML.",
        "error_generating_xml_vdj": "Não foi possível gerar o arquivo XML:\n{error}",
        "db_file_select_vdj_export": "Selecionar Banco de Dados Engine DJ (m.db)",
        "db_selection_cancelled": "Seleção de banco de dados cancelada.",
        "exported_tracks_from_dbs_count": "Exportadas {num_tracks} faixas de {num_dbs} banco(s).",
        "success_vdj_import": "A playlist '{playlist_name}' foi distribuída e sincronizada com sucesso nos discos detectados!",
        "export_title": "Exportar",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestino: {dest_path}",
        "csv_converter_title": "Engine DJ CSV para Virtual DJ XML Converter",
        "playlist_converter_header": "Conversor de Playlist",
        "csv_file_label": "Arquivo CSV do Engine DJ:",
        "ready_to_convert": "Pronto para converter.",
        "convert_to_xml_btn": "Transformar em XML",
        "error_select_valid_csv": "Selecione um arquivo CSV válido.",
        "success_tracks_converted": "Sucesso! {count} músicas convertidas.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exportada ({num_tracks} faixas unificadas).\n\nArquivo: {output_file_path}",
        "success_xml_generated": "Playlist XML gerada com sucesso!\n{count} músicas processadas.",
        "error_conversion_title": "Erro na Conversão",
        "error_processing_csv": "Ocorreu um erro ao processar o CSV:\n{error}"
    },
    "en": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Music Folder (Computer):",
        "db_file": "Database File (m.db):",
        "playlist": "Root Playlist:",
        "backup": "Auto-Backup Database",
        "status_backup": "Creating database backup...",
        "hotcue": "Import Hotcues from MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Overwrite existing hotcues in Engine DJ [SLOW PROCESS]",
        "remover_orfas": "Remove orphan tracks (missing from PC) from Playlist and Collection",
        "status_hotcue": "Importing hotcue: {filename}...",
        "browse": "Browse",
        "sync_btn": "Start Synchronization",
        "cancel_btn": "Cancel Synchronization",
        "cancel_title": "Confirm",
        "cancel_msg": "Do you really want to stop the synchronization?\n\nNo changes will be saved to the Engine DJ",
        "status_cancelled": "Synchronization cancelled by user.",
        "status_idle": "Ready to start. Make sure Engine DJ is closed.",
        "status_counting": "Counting audio files...",
        "status_fase1": "Phase 1: Mapping files ({current}/{total})...",
        "status_fase2": "Phase 2: Rebuilding Playlist tree...",
        "status_saving": "Phase 3: Saving to database...",
        "status_cancelled": "Synchronization cancelled by user.",
        "status_done": "Synchronization completed successfully!",
        "status_exporting_vdj": "Exporting '{playlist_name}' to {dest_path}...",
        "status_export_vdj_complete": "Export of '{playlist_name}' completed (placeholder).",
        "status_extracting_playlist_info": "Extracting playlist info for '{playlist_name}'...",
        "status_playlist_info_exported": "Playlist info exported to: {output_file_path}",
        "status_reading_vdj_playlist": "Reading VDJ playlist...",
        "status_collecting_tracks_vdj": "Collecting tracks from '{playlist_name}'...",
        "importing_tracks_to_drive": "Importing {count} tracks to drive {drive} database...",
        "status_import_complete": "Import completed: {processed_count} tracks on {num_drives} drives.",
        "error_db": "Error: m.db file not found!",
        "error_paths": "Please select the paths before starting.",
        "error_different_drives": "Error: The music folder and the database must be on the same drive (e.g., both on C: or both on D:).",
        "error_title": "Error",
        "error_select_engine_db": "Please select a valid Engine DJ database.",
        "error_db_file_not_found_vdj_export": "Error: Database file not found.",
        "error_select_playlist_to_export": "Please select a playlist to export.",
        "error_vdj_dest_not_found": "VirtualDJ destination folder not identified.",
        "error_export_title": "Export Error",
        "error_exporting_playlist_info": "Error exporting playlist info: {error}",
        "error_exporting_playlist_info_detail": "Could not export playlist information:\n{error}",
        "error_select_valid_playlist_to_view": "Select a valid playlist to view its content.",
        "error_select_valid_vdj_xml": "Select a valid VirtualDJ XML file.",
        "error_import_title": "Import Error",
        "error_importing_vdj_playlist": "Error: {error}",
        "error_importing_vdj_playlist_detail": "Could not process the playlist:\n{error}",
        "error_exporting_vdj_generic": "Export error: {error}",
        "error_reading_xml": "Error reading XML: {error}",
        "success_msg": "Operation finished!\nNew tracks injected: {novas}\nOrphan tracks removed: {apagadas}\nYour collection is synced.",
        "collection_name": "- MY COLLECTION", # Actual playlist name
        "collection_name_display": "- MY COLLECTION", # Display name
        "engine_sync_title": "ENGINE DJ SYNC",
        "log_checkbox": "LOG",
        "debug_checkbox": "DEBUG",
        "select_playlist_full_path": "Select Playlist (Full Path):",
        "playlist_label": "Root Playlist:",
        "vdj_target_label": "Destination in Virtual DJ:",
        "vdj_export_btn_action": "Export Selected Playlist",
        "export_engine_info_btn": "Export Playlist Info (Engine)",
        "will_be_created_suffix": " (New, will be created)",
        "donation_text": "Did this app help you? Would you like to encourage me to keep it\nupdated by buying me a coffee? ☕ Click here ☺️",
        "update_title": "Update Available!",
        "update_msg": "A new version of Engine Sync is available!\n\nYour version: {}\nNew version: {}\n\nWould you like to download it now?",
        "btn_yes": "Download Now",
        "btn_no": "Remind Me Later",
        "success_title": "Success",
        "success_playlist_exported_vdj_status": "Success! '{playlist_name}' exported.",
        "select_tool_prompt": "Select the desired tool:",
        "mirror_sync_btn": "Mirror Sync (Folder → Engine DJ)",
        "confirm_playlist_title": "Confirm Root Playlist",
        "sync_vdj_btn": "Sync VDJ (Engine ⟷ Virtual DJ)",
        "confirm_playlist_msg": "The selected target playlist ({playlist}) is different from the folder name ({folder}).\n\nThis will RESTRUCTURE the playlist '{playlist}' to mirror the folder.\n\nDo you want to continue?",
        "dbs_found": "Engine Databases found: {count}",
        "error_no_db_on_drive": "Error: No Engine DJ database found on drive {drive}.\nMake sure the 'Engine Library' folder exists on the root of this drive.",
        "vdj_back_btn": "Back to Sync DJ",
        "vdj_export_btn": "Export Engine DJ Playlist to VDJ",
        "vdj_import_btn": "Import VDJ Playlist to Engine DJ",
        "vdj_sync_title": "Sync VDJ",
        "vdj_sync_description": "Virtual DJ Synchronization Interface",
        "vdj_config_label": "Configuration: {settings}",
        "engine_dbs_detected": "Engine Databases detected: {count}",
        "all_dbs_label": ">>> ALL LOCATED DATABASES <<<",
        "not_found": "Not found",
        "vdj_mylists_label": "MyLists:",
        "vdj_mylists_not_found": "MyLists subfolders not found on drives.",
        "content_title": "Content: {title}",
        "music_list_header": "Music List: {title}",
        "no_tracks_in_playlist": "No tracks found in this playlist.",
        "no_playlists_found_in_db_vdj_export": "No playlists found in this database.",
        "error_loading_playlists_vdj_export": "Error loading playlists: {error}",
        "multi_db_mode_active": "Multi-Database mode active ({count} drives).",
        "playlists_loaded_count": "{count} playlists loaded.",
        "no_playlists_found_generic": "No playlists found.",
        "error_select_playlist_to_import_vdj": "Please select a playlist to import.",
        "no_tracks_found_in_playlist_vdj_export": "No tracks found in '{playlist_name}'.",
        "vdj_export_success_msg_detail": "Playlist exported to Virtual DJ!\n{num_tracks} tracks processed.\n{hybrid_msg}\n\nFile: {output_file}",
        "hybrid_playlist_detected_msg": " (Hybrid Playlist detected on {num_drives} drives)",
        "close_btn": "Close",
        "select_vdj_playlist_label": "Select VirtualDJ Playlist (.vdjfolder):",
        "view_tracks_btn": "View Tracks",
        "dbs_found_label": "Engine DJ Databases Found: {dbs_info}",
        "select_playlist_to_start": "Select playlist to start",
        "start_import_vdj_btn": "Start Import to Engine DJ",
        "warning_title": "Warning",
        "warning_no_tracks_in_xml": "No tracks found in the XML file.",
        "error_generating_xml_vdj": "Could not generate XML file:\n{error}",
        "db_file_select_vdj_export": "Select Engine DJ Database (m.db)",
        "db_selection_cancelled": "Database selection cancelled.",
        "exported_tracks_from_dbs_count": "Exported {num_tracks} tracks from {num_dbs} database(s).",
        "success_vdj_import": "Playlist '{playlist_name}' successfully distributed and synced across detected drives!",
        "export_title": "Export",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestination: {dest_path}",
        "csv_converter_title": "Engine DJ CSV to Virtual DJ XML Converter",
        "playlist_converter_header": "Playlist Converter",
        "csv_file_label": "Engine DJ CSV File:",
        "ready_to_convert": "Ready to convert.",
        "convert_to_xml_btn": "Convert to XML",
        "error_select_valid_csv": "Select a valid CSV file.",
        "success_tracks_converted": "Success! {count} tracks converted.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exported ({num_tracks} unified tracks).\n\nFile: {output_file_path}",
        "success_xml_generated": "Playlist XML successfully generated!\n{count} tracks processed.",
        "error_conversion_title": "Conversion Error",
        "error_processing_csv": "An error occurred while processing the CSV:\n{error}"
    },
    "es": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Carpeta de Música (PC):",
        "db_file": "Base de Datos (m.db):",
        "playlist": "Playlist Raiz:",
        "backup": "Hacer Copia de Seguridad Automática",
        "status_backup": "Creando copia de seguridad...",
        "hotcue": "Importar Hotcues del MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescribir hotcues existentes en Engine DJ [PROCESO DEMORADO]",
        "remover_orfas": "Eliminar canciones huérfanas de la lista de reproducción y de la colección",
        "status_hotcue": "Importando hotcue: {filename}...",
        "browse": "Buscar",
        "sync_btn": "Iniciar Sincronización",
        "cancel_btn": "Cancelar Sincronización",
        "cancel_title": "Confirmar",
        "cancel_msg": "¿Realmente desea interrumpir la sincronización?\n\nNo se guardarán cambios en Engine DJ",
        "status_cancelled": "Sincronización cancelada por el usuario.",
        "status_idle": "Listo para empezar. Cierre Engine DJ antes.",
        "status_counting": "Contando arquivos de audio...",
        "status_fase1": "Phase 1: Mapeando archivos ({current}/{total})...",
        "status_fase2": "Phase 2: Reconstruyendo árbol de Playlists...",
        "status_saving": "Phase 3: Guardando en la base de datos...",
        "status_cancelled": "Sincronización cancelada por el usuario.",
        "status_done": "¡Sincronización completada con éxito!",
        "status_exporting_vdj": "Exportando '{playlist_name}' a {dest_path}...",
        "status_export_vdj_complete": "Exportación de '{playlist_name}' completada (marcador de posición).",
        "status_extracting_playlist_info": "Extrayendo información de la playlist '{playlist_name}'...",
        "status_playlist_info_exported": "Información de la playlist exportada a: {output_file_path}",
        "status_reading_vdj_playlist": "Leyendo playlist VDJ...",
        "status_collecting_tracks_vdj": "Recopilando pistas de '{playlist_name}'...",
        "importing_tracks_to_drive": "Importando {count} pistas al banco del disco {drive}...",
        "status_import_complete": "Importación completada: {processed_count} pistas en {num_drives} discos.",
        "error_db": "¡Error: Archivo m.db no encontrado!",
        "error_paths": "Por favor, seleccione las rutas antes de empezar.",
        "error_different_drives": "Error: La carpeta de música y la base de datos deben estar en el mismo disco (ej: ambos en C: o ambos en D:).",
        "error_title": "Error",
        "error_select_engine_db": "Por favor, seleccione una base de datos Engine DJ válida.",
        "error_db_file_not_found_vdj_export": "Error: Archivo de base de datos no encontrado.",
        "error_select_playlist_to_export": "Por favor, seleccione una playlist para exportar.",
        "error_vdj_dest_not_found": "Carpeta de destino de VirtualDJ no identificada.",
        "error_export_title": "Error de Exportación",
        "error_exporting_playlist_info": "Error al exportar información de la playlist: {error}",
        "error_exporting_playlist_info_detail": "No se pudo exportar la información de la playlist:\n{error}",
        "error_select_valid_playlist_to_view": "Seleccione una playlist válida para ver su contenido.",
        "error_select_valid_vdj_xml": "Seleccione un archivo XML de VirtualDJ válido.",
        "error_import_title": "Error de Importación",
        "error_importing_vdj_playlist": "Error: {error}",
        "error_importing_vdj_playlist_detail": "No se pudo procesar la playlist:\n{error}",
        "error_exporting_vdj_generic": "Error de exportación: {error}",
        "error_reading_xml": "Error al leer XML: {error}",
        "success_msg": "¡Operación finalizada!\nNuevas canciones inyectadas: {novas}\nCanciones eliminadas (huérfanas): {apagadas}\nSu colección está sincronizada.",
        "collection_name": "- MY COLLECTION", # Nombre real de la playlist
        "collection_name_display": "- MY COLLECTION", # Nombre para mostrar
        "engine_sync_title": "ENGINE DJ SYNC",
        "log_checkbox": "LOG",
        "debug_checkbox": "DEBUG",
        "select_playlist_full_path": "Seleccionar Playlist (Ruta Completa):",
        "playlist_label": "Playlist Raiz:",
        "vdj_target_label": "Destino en Virtual DJ:",
        "vdj_export_btn_action": "Exportar Playlist Seleccionada",
        "export_engine_info_btn": "Exportar Info de la Playlist (Engine)",
        "will_be_created_suffix": " (Nova, Se Creará)",
        "donation_text": "¿Te ha resultado útil esta aplicación? ¿Te gustaría animarme a seguir\nactualizándola invitándome a un café? ☕ Haz clic aquí ☺️",
        "update_title": "¡Actualización Disponible!",
        "update_msg": "¡Una nova versión de Engine Sync está disponible!\n\nTu versão: {}\nNueva versión: {}\n\n¿Quieres descargarla ahora?",
        "btn_yes": "Descargar Ahora",
        "btn_no": "Recordarme Más Tarde",
        "success_title": "Éxito",
        "success_playlist_exported_vdj_status": "¡Éxito! '{playlist_name}' exportada.",
        "select_tool_prompt": "Seleccione la herramienta deseada:",
        "mirror_sync_btn": "Mirror Sync (Carpeta → Engine DJ)",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "sync_vdj_btn": "Sync VDJ (Engine ⟷ Virtual DJ)",
        "confirm_playlist_msg": "La lista de reproducción de destino seleccionada ({playlist}) é diferente del nombre de la carpeta ({folder}).\n\nEsto REESTRUCTURARÁ la lista '{playlist}' para reflejar la carpeta.\n\n¿Desea continuar?",
        "vdj_export_btn": "Exportar Playlist de Engine DJ a VDJ",
        "vdj_import_btn": "Importar Playlist de VDJ a Engine DJ",
        "vdj_sync_title": "Sincronizar VDJ",
        "vdj_sync_description": "Interfaz de Sincronización Virtual DJ",
        "vdj_config_label": "Configuración: {settings}",
        "engine_dbs_detected": "Bases de Datos Engine detectadas: {count}",
        "all_dbs_label": ">>> TODAS LAS BASES DE DATOS LOCALIZADAS <<<",
        "not_found": "No encontrada",
        "vdj_mylists_label": "MisListas:",
        "vdj_mylists_not_found": "Subcarpetas 'MyLists' no encontradas en los discos.",
        "content_title": "Contenido: {title}",
        "music_list_header": "Lista de Canciones: {title}",
        "no_tracks_in_playlist": "Ninguna canción encontrada en esta playlist.",
        "no_playlists_found_in_db_vdj_export": "Ninguna playlist encontrada en esta base de datos.",
        "error_loading_playlists_vdj_export": "Error al cargar playlists: {error}",
        "multi_db_mode_active": "Modo Multi-Base de Datos activo ({count} discos).",
        "playlists_loaded_count": "{count} playlists cargadas.",
        "no_playlists_found_generic": "Ninguna playlist encontrada.",
        "error_select_playlist_to_import_vdj": "Por favor, seleccione una playlist para importar.",
        "no_tracks_found_in_playlist_vdj_export": "Ninguna pista encontrada en '{playlist_name}'.",
        "vdj_export_success_msg_detail": "¡Playlist exportada a Virtual DJ!\n{num_tracks} pistas procesadas.\n{hybrid_msg}\n\nArchivo: {output_file}",
        "hybrid_playlist_detected_msg": " (Playlist Híbrida detectada en {num_drives} discos)",
        "close_btn": "Cerrar",
        "select_vdj_playlist_label": "Seleccionar Playlist de VirtualDJ (.vdjfolder):",
        "view_tracks_btn": "Ver Canciones",
        "dbs_found_label": "Bases de Datos de Engine DJ Encontradas: {dbs_info}",
        "select_playlist_to_start": "Seleccione la playlist para empezar",
        "start_import_vdj_btn": "Iniciar Importación a Engine DJ",
        "warning_title": "Advertencia",
        "warning_no_tracks_in_xml": "Ninguna pista encontrada en el archivo XML.",
        "error_generating_xml_vdj": "No se pudo generar el archivo XML:\n{error}",
        "db_file_select_vdj_export": "Seleccionar Base de Datos Engine DJ (m.db)",
        "db_selection_cancelled": "Selección de base de datos cancelada.",
        "exported_tracks_from_dbs_count": "Exportadas {num_tracks} pistas de {num_dbs} base(s) de datos.",
        "success_vdj_import": "¡La playlist '{playlist_name}' fue distribuida y sincronizada con éxito en los discos detectados!",
        "export_title": "Exportar",
        "export_vdj_confirm_msg": "Playlist: {playlist_name}\nDestino: {dest_path}",
        "csv_converter_title": "Convertidor de CSV de Engine DJ a XML de Virtual DJ",
        "playlist_converter_header": "Convertidor de Playlist",
        "csv_file_label": "Archivo CSV de Engine DJ:",
        "ready_to_convert": "Listo para convertir.",
        "convert_to_xml_btn": "Transformar a XML",
        "error_select_valid_csv": "Seleccione un archivo CSV válido.",
        "success_tracks_converted": "¡Éxito! {count} canciones convertidas.",
        "success_playlist_info_exported_detail_vdj": "Playlist '{playlist_name}' exportada ({num_tracks} pistas unificadas).\n\nArchivo: {output_file_path}",
        "success_xml_generated": "¡Playlist XML generada con éxito!\n{count} canciones procesadas.",
        "error_conversion_title": "Error de Conversión",
        "error_processing_csv": "Ocurrió un error al procesar el CSV:\n{error}"
    }
}