VERSAO_ATUAL = "v2.0.9"
URL_DOACAO = "https://linktr.ee/leh.deejay82"
GITHUB_API_URL = "https://api.github.com/repos/lehdeejay82/Engine-Sync/releases/latest"
GITHUB_RELEASE_URL = "https://github.com/lehdeejay81/Engine-Sync/releases/latest" # Corrected to lehdeejay81

STRINGS = {
    "pt": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Pasta de Músicas (PC):",
        "db_file": "Banco de Dados (m.db):",
        "playlist": "Playlist Raiz:",
        "backup": "Fazer Backup Automático",
        "status_backup": "Criando backup do banco de dados...",
        "hotcue": "Importar Hotcues do MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescrever hotcues existentes no banco [PROCESSO DEMORADO]",
        "remover_orfas": "Remover músicas órfãs (faltantes no PC) da Playlist e da Coleção",
        "status_hotcue": "Importando hotcue: {filename}...",
        "browse": "Procurar",
        "sync_btn": "Iniciar Sincronização",
        "cancel_btn": "Cancelar Sincronização",
        "cancel_title": "Confirmar",
        "cancel_msg": "Deseja realmente interromper a sincronização?\n\nNenhuma alteração será gravada no banco de dados.",
        "status_cancelled": "Sincronização cancelada pelo usuário.",
        "status_idle": "Pronto para iniciar. Verifique se o Engine está fechado.",
        "status_counting": "Contando arquivos de áudio...",
        "status_fase1": "Fase 1: Mapeando arquivos ({current}/{total})...",
        "status_fase2": "Fase 2: Reconstruindo a árvore de Playlists...",
        "status_saving": "Fase 3: Gravando no banco de dados...",
        "status_done": "Sincronização concluída com sucesso!",
        "error_db": "Erro: Arquivo m.db não encontrado!",
        "error_paths": "Por favor, selecione as pastas antes de iniciar.",
        "error_different_drives": "Erro: A pasta de músicas e o banco de dados devem estar no mesmo disco (ex: ambos no C: ou ambos no D:).",
        "success_msg": "Operação finalizada!\nMúsicas novas injetadas: {novas}\nMúsicas apagadas (órfãs): {apagadas}\nSua coleção foi sincronizada.",
        "collection_name": "- MY COLLECTION", # Nome real da playlist
        "collection_name_display": "- MY COLLECTION", # Nome para exibição
        "will_be_created_suffix": " (Nova, será criada)",
        "donation_text": "Este app te ajudou? Gostaria de me incentivar a mante-lo atualizado\nme pagando um cafezinho? ☕ Clique aqui ☺️",
        "update_title": "Atualização Disponível!",
        "update_msg": "Uma nova versão do Engine Sync está disponível!\n\nSua versão: {}\nNova versão: {}\n\nDeseja baixar a atualização agora?",
        "btn_yes": "Baixar Agora",
        "btn_no": "Lembrar Depois",
        "success_title": "Sucesso",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "confirm_playlist_msg": "A playlist alvo selecionada ({playlist}) é diferente do nome da pasta ({folder}).\n\nIsso irá REESTRUTURAR a playlist '{playlist}' para espelhar a pasta.\n\nDeseja continuar?",
        "sync_vdj_msg": "Funcionalidade de sincronização com Virtual DJ em desenvolvimento.",
        "vdj_back_btn": "Voltar para Sync DJ",
        "vdj_import_btn": "Exportar Playlist do Engine para o VDJ",
        "vdj_export_btn": "Exportar Playlist do VDJ para o Engine"
    },
    "en": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Music Folder (Computer):",
        "db_file": "Database File (m.db):",
        "playlist": "Root Playlist:",
        "backup": "Auto-Backup Database",
        "status_backup": "Creating database backup...",
        "hotcue": "Import Hotcues from MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Overwrite existing hotcues in database [SLOW PROCESS]",
        "remover_orfas": "Remove orphan tracks (missing from PC) from Playlist and Collection",
        "status_hotcue": "Importing hotcue: {filename}...",
        "browse": "Browse",
        "sync_btn": "Start Synchronization",
        "cancel_btn": "Cancel Synchronization",
        "cancel_title": "Confirm",
        "cancel_msg": "Do you really want to stop the synchronization?\n\nNo changes will be saved to the database.",
        "status_cancelled": "Synchronization cancelled by user.",
        "status_idle": "Ready to start. Make sure Engine DJ is closed.",
        "status_counting": "Counting audio files...",
        "status_fase1": "Phase 1: Mapping files ({current}/{total})...",
        "status_fase2": "Phase 2: Rebuilding Playlist tree...",
        "status_saving": "Phase 3: Saving to database...",
        "status_done": "Synchronization completed successfully!",
        "error_db": "Error: m.db file not found!",
        "error_paths": "Please select the paths before starting.",
        "error_different_drives": "Error: The music folder and the database must be on the same drive (e.g., both on C: or both on D:).",
        "success_msg": "Operation finished!\nNew tracks injected: {novas}\nOrphan tracks removed: {apagadas}\nYour collection is synced.",
        "collection_name": "- MY COLLECTION", # Actual playlist name
        "collection_name_display": "- MY COLLECTION", # Display name
        "will_be_created_suffix": " (New, will be created)",
        "donation_text": "Did this app help you? Would you like to encourage me to keep it\nupdated by buying me a coffee? ☕ Click here ☺️",
        "update_title": "Update Available!",
        "update_msg": "A new version of Engine Sync is available!\n\nYour version: {}\nNew version: {}\n\nWould you like to download it now?",
        "btn_yes": "Download Now",
        "btn_no": "Remind Me Later",
        "success_title": "Success",
        "confirm_playlist_title": "Confirm Root Playlist",
        "confirm_playlist_msg": "The selected target playlist ({playlist}) is different from the folder name ({folder}).\n\nThis will RESTRUCTURE the playlist '{playlist}' to mirror the folder.\n\nDo you want to continue?",
        "sync_vdj_msg": "Virtual DJ synchronization feature under development.",
        "vdj_back_btn": "Back to Sync DJ",
        "vdj_import_btn": "Export Engine Playlist to VDJ",
        "vdj_export_btn": "Export VDJ Playlist to Engine"
    },
    "es": {
        "title": "Engine DJ - Mirror Sync",
        "music_folder": "Carpeta de Música (PC):",
        "db_file": "Base de Datos (m.db):",
        "playlist": "Playlist Raiz:",
        "backup": "Hacer Copia de Seguridad Automática",
        "status_backup": "Creando copia de seguridad...",
        "hotcue": "Importar Hotcues del MP3 (Mixed In Key / Serato)",
        "hotcue_overwrite": "  ↳  Sobrescribir hotcues existentes en la base de datos [PROCESO DEMORADO]",
        "remover_orfas": "Eliminar canciones huérfanas de la lista de reproducción y de la colección",
        "status_hotcue": "Importando hotcue: {filename}...",
        "browse": "Buscar",
        "sync_btn": "Iniciar Sincronización",
        "cancel_btn": "Cancelar Sincronización",
        "cancel_title": "Confirmar",
        "cancel_msg": "¿Realmente desea interrumpir la sincronización?\n\nNo se guardarán cambios en la base de datos.",
        "status_cancelled": "Sincronización cancelada por el usuario.",
        "status_idle": "Listo para empezar. Cierre Engine DJ antes.",
        "status_counting": "Contando arquivos de audio...",
        "status_fase1": "Phase 1: Mapeando archivos ({current}/{total})...",
        "status_fase2": "Phase 2: Reconstruyendo árbol de Playlists...",
        "status_saving": "Phase 3: Guardando en la base de datos...",
        "status_done": "¡Sincronización completada con éxito!",
        "error_db": "¡Error: Archivo m.db no encontrado!",
        "error_paths": "Por favor, seleccione las rutas antes de empezar.",
        "error_different_drives": "Error: La carpeta de música y la base de datos deben estar en el mismo disco (ej: ambos en C: o ambos en D:).",
        "success_msg": "¡Operación finalizada!\nNuevas canciones inyectadas: {novas}\nCanciones eliminadas (huérfanas): {apagadas}\nSu colección está sincronizada.",
        "collection_name": "- MY COLLECTION", # Nombre real de la playlist
        "collection_name_display": "- MY COLLECTION", # Nombre para mostrar
        "will_be_created_suffix": " (Nova, Se Creará)",
        "donation_text": "¿Te ha resultado útil esta aplicación? ¿Te gustaría animarme a seguir\nactualizándola invitándome a un café? ☕ Haz clic aquí ☺️",
        "update_title": "¡Actualización Disponible!",
        "update_msg": "¡Una nova versión de Engine Sync está disponible!\n\nTu versão: {}\nNueva versión: {}\n\n¿Quieres descargarla ahora?",
        "btn_yes": "Descargar Ahora",
        "btn_no": "Recordarme Más Tarde",
        "success_title": "Éxito",
        "confirm_playlist_title": "Confirmar Playlist Raiz",
        "confirm_playlist_msg": "La lista de reproducción de destino seleccionada ({playlist}) é diferente del nombre de la carpeta ({folder}).\n\nEsto REESTRUCTURARÁ la lista '{playlist}' para reflejar la carpeta.\n\n¿Desea continuar?",
        "sync_vdj_msg": "Funcionalidade de sincronização com Virtual DJ em desenvolvimento.",
        "vdj_import_btn": "Exportar Playlist de Engine a VDJ",
        "vdj_export_btn": "Exportar Playlist de VDJ a Engine"
    }
}